### ISSUE TITLE
Feature request: Conditional sections

### ISSUE THREAD

**Issue by tychop** [mysterioustrousers/MYSForms#4]
It would be nice to be able to create cells in sections and show those sections conditionally on a model value.

**Comment by atomkirk** [comment]
I think what I'm going to do is introduce a class like `MYSFormDependency` (still pondering on the name) and to use it we'll create one of these objects with the conditions, object and reaction of the dependency and then you will just assign this dependency to any elements you want it applied to. So you might create a dependency that as long as a toggle on keyPath `wantsMoreInfo` is on, the element that has that dependency will be visible, otherwise it will be hidden. So, with this approach, there's no need for the notion of sections because you'll just assign the same dependency to a few elements that make up your conceptual "section"
