### ISSUE TITLE
Trying to create a dynamic height uitextviewcell

### ISSUE THREAD

**Issue by tychop** [mysterioustrousers/MYSForms#5]
Hi, we are trying to implement a cell with a textview that sizes itself to the size of the text in the textview.
However, when we call formElement valueDidChange the cell gets reloaded and textview looses keyboard focus.
So we can't call formElement valueDidChange from the UITextView's textViewDidChange  delegate method to resize the cell when entering text.

Do you have any tips to accomplish a self sizing cell with a textview?

We've tried stuff like http://stackoverflow.com/questions/25895311/uicollectionview-self-sizing-cells-with-auto-layout but this is something that doesn't seem to run well with MYSForms...

**Comment by atomkirk** [comment]
Give me a bit too think on this

**Comment by atomkirk** [comment]
So you want cell to change as they are typing or just on form load?

**Comment by tychop** [comment]
If people enter multiple lines in a textview cell, It would be nice to have the cell grow with the number of lines in the textview.

**Comment by tychop** [comment]
I am getting closer to dynamic cell heights by removing 
```javascript
- (CGSize)collectionView:(UICollectionView *)collectionView
                  layout:(UICollectionViewLayout *)collectionViewLayout
  sizeForItemAtIndexPath:(NSIndexPath *)indexPath
```
from MYSFormViewController and use preferredLayoutAttributesFittingAttributes in my cell classes...

**Comment by atomkirk** [comment]
Well, i wanted to take a look first, but i think the way i would go about it is by overriding the class method on the cell called sizeForCellWithElement or something like that. But im not sure if you would have to reload the page or what…  


i didnt know collection view cells were self sizing as well, i thought only table views in ios 8 did that. If so, once i decide to drop support for ios <8 then ill definitely do it that way.




The reason i based the forms on collection views was so that people could customize the layout of the form, so sublassing collectionviewflowlayout may be most "correct" way to solve this problem. But if youve got the project forked and are changing stuff up to make it work for you, have at it!


- Adam Kirk

**Comment by tychop** [comment]
Ok thanks. I'll see what I can do. If I have usefull addiditions to the framework, I'll let you know.
